### PR TITLE
AKS Maintenance Documentaion

### PR DESCRIPTION
**Pull request by splattner**

### CODE REVIEW

**Review by tobru — APPROVED** [review]
@splattner I corrected some spelling and formatting issues and applied a bunch of Antora/AsciiDoc best practices.

I'm not entirely sure if it makes sense to have this bash script as part of the documentation. Could you please get a review about that by Pollux as they are the main target group of this documentation for the time bein.

**Comment by corvus-ch** [comment]
> I'm not entirely sure if it makes sense to have this bash script as part of the documentation. Could you please get a review about that by Pollux as they are the main target group of this documentation for the time bein.

I agree but I assume the task was to write a working documentation. So this is fine by me. However, I suggest to plan for container image that contains all the required tools and the script as a follow up.

**Review by corvus-ch — APPROVED** [review]
This looks good to me and I approve under the following assumption:

* A container image will be created containing all the tools and the script currenty being put into examples.

**Comment by splattner** [comment]
thx for feedback. I agree and I will create an followup to put everything needed into a container. 
Therefore I merge this request here.

**Pull request merged**
